NOME
#Punto 6
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor de la estadística de Pillai es $P_{val} = 0.13$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \mu_1 = \mu_2 = \mu_3$.

In [ ]:
#Setting data
data<-c(1,2,1,1,1,2,1,3,2,2,2,0,2,2,2,2,4,2,2,1,1,3,3,2,3,2,3,3,6,2,3,5,3,3,3,4)
data2<-matrix(data,ncol=3,byrow=TRUE)
#print(data2)
df<-data.frame(data2)
colnames(df)<-c("sample","variable1","variable2")
print(df)

   sample variable1 variable2
1       1         2         1
2       1         1         2
3       1         3         2
4       2         2         0
5       2         2         2
6       2         4         2
7       2         1         1
8       3         3         2
9       3         2         3
10      3         6         2
11      3         5         3
12      3         3         4


In [ ]:
#ANOVA Analysis
df$sample<-as.factor(df$sample)
vars<-as.matrix(df[,-1])
#print(vars)
fit<-manova(vars~sample,data=df)
#print(fit)
summary(fit,test="Pillai")

          Df  Pillai approx F num Df den Df Pr(>F)
sample     2 0.61926   2.0183      4     18 0.1349
Residuals  9                                      

#Punto 7 - NOT DONE
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor de la estadística de Pillai es $P_{val} = 0.13$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \mu_1 = \mu_2 = \mu_3$. (BLABLABLA)

In [ ]:
#Setting data
#library(tidyverse)
t = tibble(tto = c('A','B','C'),C = c(1,-1/2,-1/2))
#print(t)
data = tibble(tto = c(rep('A',3),rep('B',4),rep('C',5)),
              y1 = c(2,1,3,2,2,4,1,3,2,6,5,3),
              y2 = c(1,2,2,0,2,2,1,2,3,2,3,4))
#print(data)
ni=c(3,4,5)
Y1 = data %>% group_by(tto) %>% 
    mutate(Y1b=mean(y1), Y2b=mean(y2)) %>%
    ungroup() %>%
    mutate(Y1bb=mean(y1), Y2bb=mean(y2))
#print(Y1)
p = 2; k = 3
Y = Y1 %>% select(paste0('y',1:p)) %>% as.matrix
#print(Y)
Yb = Y1 %>% select(paste0('Y',1:p,'b')) %>% as.matrix
#print(Yb)
Ybb = Y1 %>% select(paste0('Y',1:p,'bb')) %>% as.matrix
#print(Ybb)
E = t(Y-Yb) %*% (Y-Yb)
#print(E)
sc = data %>% group_by(tto) %>%
    summarise(Y1b = mean(y1), Y2b = mean(y2)) %>%
    inner_join(C) %>%
    ungroup() %>%
    summarize(Y1b = sum(C*Y1b), Y2b = sum(C*Y2b)) %>% ungroup() %>%
    select(Y1b,Y2b) %>% as.matrix()
print(sc)

`summarise()` ungrouping output (override with `.groups` argument)



ERROR: ignored

In [ ]:
#ANOVA Analysis
df$sample<-as.factor(df$sample)
vars<-as.matrix(df[,-1])
#print(vars)
fit<-manova(vars~sample,data=df)
#fit
summary(fit,test="Hotelling-Lawley")
summary(fit,test="Wilks")
summary(fit,test="Pillai")
summary(fit,test= "Roy")

          Df Hotelling-Lawley approx F num Df den Df  Pr(>F)  
sample     2           1.4487   2.5352      4     14 0.08693 .
Residuals  9                                                  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

          Df   Wilks approx F num Df den Df Pr(>F)
sample     2 0.40037   2.3216      4     16 0.1012
Residuals  9                                      

          Df  Pillai approx F num Df den Df Pr(>F)
sample     2 0.61926   2.0183      4     18 0.1349
Residuals  9                                      

          Df   Roy approx F num Df den Df  Pr(>F)  
sample     2 1.414    6.363      2      9 0.01895 *
Residuals  9                                       
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#Punto 8
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor de la estadística lambda de Wilks es $P_{val} = 0.26$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \mu_1 = \mu_2 = \mu_3$.


In [ ]:
#Setting data
data<-c(1,2,1,1,1,2,1,4,3,2,2,0,2,2,2,2,3,2,2,1,2,3,3,2,3,2,3,3,6,2,3,5,3,3,4,2)
data2<-matrix(data,ncol=3,byrow=TRUE)
#print(data2)
df<-data.frame(data2)
colnames(df)<-c("sample","variable1","variable2")
print(df)

   sample variable1 variable2
1       1         2         1
2       1         1         2
3       1         4         3
4       2         2         0
5       2         2         2
6       2         3         2
7       2         1         2
8       3         3         2
9       3         2         3
10      3         6         2
11      3         5         3
12      3         4         2


In [ ]:
#ANOVA Analysis
df$sample<-as.factor(df$sample)
vars<-as.matrix(df[,-1])
#print(vars)
fit<-manova(vars~sample,data=df)
#fit
summary(fit,test="Wilks")

          Df   Wilks approx F num Df den Df Pr(>F)
sample     2 0.53765   1.4552      4     16 0.2619
Residuals  9                                      

#Punto 10
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor mediante la traza de Lawley-Hotelling es $P_{val} = 0.22$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \mu_1 = \mu_2 = \mu_3$.

In [ ]:
#Setting data
data<-c(1,3,2,1,1,2,1,4,3,2,1,1,2,2,2,2,3,2,2,1,2,3,3,2,3,2,3,3,6,2,3,5,3,3,4,2)
data2<-matrix(data,ncol=3,byrow=TRUE)
#print(data2)
df<-data.frame(data2)
colnames(df)<-c("sample","variable1","variable2")
print(df)

   sample variable1 variable2
1       1         3         2
2       1         1         2
3       1         4         3
4       2         1         1
5       2         2         2
6       2         3         2
7       2         1         2
8       3         3         2
9       3         2         3
10      3         6         2
11      3         5         3
12      3         4         2


In [ ]:
#MANOVA Analysis
df$sample<-as.factor(df$sample)
vars<-as.matrix(df[,-1])
#print(vars)
fit<-manova(vars~sample,data=df)
#fit
summary(fit,"Hotelling-Lawley")

          Df Hotelling-Lawley approx F num Df den Df Pr(>F)
sample     2          0.93916   1.6435      4     14 0.2187
Residuals  9                                               

#Punto 11 - NOT DONE
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor de la estadística de Pillai es $P_{val} = 0.13$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \mu_1 = \mu_2 = \mu_3$. (BLABLABLA) As the 7th point

In [ ]:
#Same thing but differente data than in exc 7

In [ ]:
#Same thing but differente data than in exc 7

#Punto 12
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor de la estadística es $P_{val} = 0.51$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \Sigma = \begin{pmatrix}2 & 1 \\ 1 & 1 \end{pmatrix}$ 

In [ ]:
#-----Sigma test function
sigma.test<-function(Sigma_0,S,n){ #Pg235
  # numero de filas la matriz Sigma
  p<-nrow(S)
  gl<-(1/2)*p*(p+1) # grados de libertad
  # producto entre S y la inversa de Sigma_0
  Sisigma_0<-S%*%solve(Sigma_0)
  #determinante de sigma_0
  D_sigma_0<-det(Sigma_0)
  #determinante de S
  D_S<-det(S)
  # estad´ıstica lambda 5.2a
  E_lambda<-(n-1)*(log(D_sigma_0)-log(D_S)+
  sum(diag(Sisigma_0))-p)
  # estad´ıstica lambda
  E_lambda1<-(1-(1/(6*(n-1)))*(2*p+1-2/(p+1) ))* E_lambda
  p_val<-pchisq(E_lambda1,gl) # pvalor
  list(E_lambda1=E_lambda1, P_valor=p_val)
}

In [ ]:
sig0 <- c(2,1,1,1)
data <- c(2,2,3,1,0,2,2,2)
sig0M <- matrix(sig, ncol = 2, byrow = TRUE)
#print(sig0M)
dataM <- t(matrix(data, ncol = 4, byrow = TRUE))
#print(dataM)
SM<-cov(dataM)
print(SM)
# llamado de la funci´on
sigma.test(sig0M,SM,n=4)

          [,1] [,2]
[1,] 0.6666667    0
[2,] 0.0000000    1


$E_lambda1
[1] 2.442078

$P_valor
[1] 0.5141501

#Punto 14
Con un grado de significancia de $\alpha = 0.05$ y dado que el P-valor de la estadística es $P_{val} = 0.91$ (es decir $P_{val}>\alpha$) se tiene que NO se rechaza la hipótesis nula de que $H_0: \Sigma = \begin{pmatrix}2 & 1 \\ 1 & 1 \end{pmatrix}$ 

In [28]:
sig0 <- c(2,1,1,1)
data <- c(3,2,6,5,4,2,3,2,3,2)
sig0M <- matrix(sig, ncol = 2, byrow = TRUE)
#print(sig0M)
dataM <- t(matrix(data, ncol = 5, byrow = TRUE))
print(dataM)
SM<-cov(dataM)
print(SM)
# llamado de la funci´on
sigma.test(sig0M,SM,n=5)

     [,1] [,2]
[1,]    3    2
[2,]    2    3
[3,]    6    2
[4,]    5    3
[5,]    4    2
      [,1]  [,2]
[1,]  2.50 -0.25
[2,] -0.25  0.30


$E_lambda1
[1] 6.472606

$P_valor
[1] 0.9092509